### ISSUE TITLE
The connection of a Boox Note Air3C do not move the pointer

### ISSUE THREAD

**Issue by Gugus-1** [leath-dub/droidux#1]
Hello,

I tested your program on a Boox Note Air3C. While the program launches normally and works with my phone, moving my finger on the tablet or using the stylus does not move the pointer on the computer.

The device is recognized as a Wacom tablet in Ubuntu, but when I use the Wacom tablet testing interface in Ubuntu, nothing happens.

Could you help me identify the issue and get this incredible idea working with my setup?

Thank you!

**Comment by leath-dub** [comment]
could you give me the output of

```
droidux -l
```

When connected and also what devuce name you were using.

**Comment by leath-dub** [comment]
My guess is you need a hwdb entry for your device, I can help you out tomorrow ill be on and off my pc.

**Comment by leath-dub** [comment]
just in case times dont intersect, you can also refer to this part of the readme for adding the preexisting hwdb files (the boox one may work):

https://github.com/leath-dub/droidux#hwdb

Also I do apologise for such a complicated setup, because the project is trying to be more of a general solution the ux suffers.

**Comment by leath-dub** [comment]
> I tried adding the hwdb file 00-boox.hwdb in the /etc/udev/hwdb.d folder, and it worked!

Good to hear!
